[package]
name = "ostatus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "3.2.19", features = ["derive"] }
configparser = "3.0.1"
flate2 = "1.0.24"
git2 = "0.15.0"
librpm = { git = "https://github.com/rpm-software-management/librpm.rs" }
libsolv-rs = { path = "libsolv-rs" }
regex = "1.6.0"
sha2 = "0.10.2"
tempfile = "3.3.0"
xmltree = "0.10.3"

[workspace]
members = [ "libsolv-sys", "libsolv-rs" ]
