[package]
name = "ostatus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["derive"] }
configparser = "3.0.0"
flate2 = "1.0.22"
librpm = { git = "https://github.com/rpm-software-management/librpm.rs" }
libsolv-rs = { path = "libsolv-rs" }
regex = "1.5.4"
sha2 = "0.10.1"
xmltree = "0.10.3"

[workspace]
members = [ "libsolv-sys", "libsolv-rs" ]
